### PR TITLE
Update zoneinfo from 2013b to 2016c. Close #6

### LINKED ISSUE #6: Upgrade to zoneinfo 2016c
Currently using 2013b.
Latests db: https://www.iana.org/time-zones
Can't find a changelog (apparently they don't keep one), but since 2013b IANA released about 25 new versions.

Why it affected us: Moscow changed it's timezone from UTC+4 to UTC+3 in 2014. 
Wondering if we also need to update any code as well.

### PR DESCRIPTION
**Pull request by ana-balica**

### CODE REVIEW

**Comment by moggers87** [comment]
Could you update [OLSON_VERSION](https://github.com/potatolondon/gae-pytz/blob/master/pytz/__init__.py#L12) too?

**Comment by ana-balica** [comment]
Updated also `__version__`.
Didn't get why it's `__version__ = OLSON_VERSION + '-1'`?
Obviously can revert back if there's a reason.

**Comment by moggers87** [comment]
That's for patch releaeses, but I don't think that's an issue here as this library is not available on PyPI

**Comment by davidwtbuxton** [comment]
Excellent. Thank you @ana-balica

**Pull request merged**
